kind: pipeline
type: exec
name: deploy-personal-website

steps:
  - name: build svelte docker image
    commands:
      - docker build -t my-svelte-app .

  - name: restart svelte container
    commands:
      - docker stop my-svelte-app || true
      - docker rm my-svelte-app || true
      - docker run -d --name my-svelte-app -p 3000:3000 my-svelte-app
