kind: pipeline
type: exec
name: deploy-personal-website

steps:
  - name: build svelte docker image
    commands:
      - docker build -t svelte-app .

  - name: restart svelte container
    commands:
      - docker stop svelte-app || true
      - docker rm svelte-app || true
      - docker run -d --name svelte-app -p 3000:3000 svelte-app
